server:
  port: 8081

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/gym?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: 8667663378
  redis:
    host: localhost
    port: 6379
    database: 0

mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.zhc.entity
  configuration:
    #??????
    map-underscore-to-camel-case: true

sky:
  jwt:
    secret-key: zhenghaochangdetoken
    time-mill: 86400000  #????:??
    token-name: authorization
